server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com  #eureka服务端的实例名称
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己
    fetch-registry: false   #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  #关闭自我保护机制，保证不可用服务被及时剔除
#  server:
#    enable-self-preservation: false
#    #eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒
#    eviction-interval-timer-in-ms: 2000