server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
      - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
       #匹配后提供服务的路由地址
#          uri: http://localhost:8001
        uri: lb://CLOUD-PAYMENT-SERVICE
#          配置断言  满足断言所有条件才能访问 否则404
        predicates:
        - Path=/payment/get/** # 断言，路径相匹配的进行路由
#        - Before=2020-08-17T20:29:47.947+08:00[Asia/Shanghai]  #在这个时间之前才可以访问
#        - Between=2020-08-17T19:29:47.947+08:00[Asia/Shanghai],2020-08-17T20:29:47.947+08:00[Asia/Shanghai]  #在这个时间之间才可以访问
#        - Cookie=name, zp   #有这个cookie才能访问
#        - Host=**.zp.com,**.zpzp.com
#        - Method=GET  #GET请求才能访问
      - id: payment_route2
#          uri: http://localhost:8001
        uri: lb://CLOUD-PAYMENT-SERVICE
        predicates:
        - Path=/payment/lb/** #断言,路径相匹配的进行路由
#        - After=2020-08-17T20:29:47.947+08:00[Asia/Shanghai]  #在这个时间之后才可以访问
#        - Between=2020-08-17T21:29:47.947+08:00[Asia/Shanghai],2020-08-17T22:29:47.947+08:00[Asia/Shanghai]
#        - Header=X-Request-Id, \d+
#        - Query=username, \d+  #要有参数username且值为正整数才能路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/